apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: bookstore-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: yuchingt/book-service:latest
          imagePullPolicy: Always
          env:
            # URL THING
            - name: BOOKS_SERVICE_URL
              value: 'http://book-service.bookstore-ns.svc.cluster.local'
            - name: CUSTOMERS_SERVICE_URL
              value: 'http://customer-service.bookstore-ns.svc.cluster.local'

            # Recommendation service URL directly here
            - name: RECOMMENDATION_SERVICE_URL
              #value: 'http://18.118.230.221:80' # gradescope
              value: 'http://3.130.6.49:80' # aws

            # DB THING
            - name: DB_HOST
              value: 'bookstore-db-dev.cluster-c0xfwrcckgis.us-east-1.rds.amazonaws.com'
            - name: DB_PORT
              value: '3306'
            - name: DB_USER
              value: 'admin'
            - name: DB_PASSWORD
              value: 'adminadmin'
            - name: DB_NAME
              value: 'bookstore'
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
