apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: bookstore-ns
spec:
  selector:
    app: book-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
