apiVersion: v1
kind: Service
metadata:
  name: bff-mobile
  namespace: bookstore-ns
spec:
  selector:
    app: bff-mobile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
